language: go
go:
- '1.14.x'
install: true
script:
- go test -v ./...
- go build -o verbumsrvr github.com/verbumby/verbum/backend/cmd/verbumsrvr
- go build -o verbumctl github.com/verbumby/verbum/backend/cmd/verbumctl
- deploy/deb.bash
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy/deploy.bash
  on:
    branch: master
