language: go
go:
- '1.11'
install: true
script:
- go test -v ./...
- go build -o verbumsrvr github.com/verbumby/verbum/backend/cmd/verbum
- go build -o verbumctl github.com/verbumby/verbum/backend/cmd/rvblr
- deploy/deb.bash
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy/deploy.bash
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_a25db77e2a26_key -iv $encrypted_a25db77e2a26_iv
  -in deploy/id_ed25519.enc -out deploy/id_ed25519 -d
