version: '3.4'
services:
  db:
    image: mariadb:10.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=verbum
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./db/data:/var/lib/mysql

  sphinx:
    build: ./sphinx
    ports:
      - "9306:9306"
    volumes:
      - ./sphinx/data:/var/data
      - ./sphinx/logs:/var/log

  elastic:
    build: ./elastic
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
