version: '3.4'
services:
  elastic:
    build: ./elastic
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
      - ./elastic/backup:/usr/share/elasticsearch/backups/backup
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - "5601:5601"
