// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package typeahead

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type typeaheadTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *typeaheadTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("typeaheads").
func (v *typeaheadTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *typeaheadTableType) Columns() []string {
	return []string{"id", "typeahead", "article_id"}
}

// NewStruct makes a new struct for that view or table.
func (v *typeaheadTableType) NewStruct() reform.Struct {
	return new(Typeahead)
}

// NewRecord makes a new record for that table.
func (v *typeaheadTableType) NewRecord() reform.Record {
	return new(Typeahead)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *typeaheadTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// TypeaheadTable represents typeaheads view or table in SQL database.
var TypeaheadTable = &typeaheadTableType{
	s: parse.StructInfo{Type: "Typeahead", SQLSchema: "", SQLName: "typeaheads", Fields: []parse.FieldInfo{{Name: "ID", Type: "int32", Column: "id"}, {Name: "Typeahead", Type: "string", Column: "typeahead"}, {Name: "ArticleID", Type: "int32", Column: "article_id"}}, PKFieldIndex: 0},
	z: new(Typeahead).Values(),
}

// String returns a string representation of this struct or record.
func (s Typeahead) String() string {
	res := make([]string, 3)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Typeahead: " + reform.Inspect(s.Typeahead, true)
	res[2] = "ArticleID: " + reform.Inspect(s.ArticleID, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Typeahead) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Typeahead,
		s.ArticleID,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Typeahead) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Typeahead,
		&s.ArticleID,
	}
}

// View returns View object for that struct.
func (s *Typeahead) View() reform.View {
	return TypeaheadTable
}

// Table returns Table object for that record.
func (s *Typeahead) Table() reform.Table {
	return TypeaheadTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Typeahead) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Typeahead) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Typeahead) HasPK() bool {
	return s.ID != TypeaheadTable.z[TypeaheadTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Typeahead) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int32(i64)
	} else {
		s.ID = pk.(int32)
	}
}

// check interfaces
var (
	_ reform.View   = TypeaheadTable
	_ reform.Struct = (*Typeahead)(nil)
	_ reform.Table  = TypeaheadTable
	_ reform.Record = (*Typeahead)(nil)
	_ fmt.Stringer  = (*Typeahead)(nil)
)

func init() {
	parse.AssertUpToDate(&TypeaheadTable.s, new(Typeahead))
}
