// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package headword

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type headwordTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *headwordTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("headwords").
func (v *headwordTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *headwordTableType) Columns() []string {
	return []string{"id", "headword", "article_id"}
}

// NewStruct makes a new struct for that view or table.
func (v *headwordTableType) NewStruct() reform.Struct {
	return new(Headword)
}

// NewRecord makes a new record for that table.
func (v *headwordTableType) NewRecord() reform.Record {
	return new(Headword)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *headwordTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// HeadwordTable represents headwords view or table in SQL database.
var HeadwordTable = &headwordTableType{
	s: parse.StructInfo{Type: "Headword", SQLSchema: "", SQLName: "headwords", Fields: []parse.FieldInfo{{Name: "ID", Type: "int32", Column: "id"}, {Name: "Headword", Type: "string", Column: "headword"}, {Name: "ArticleID", Type: "int32", Column: "article_id"}}, PKFieldIndex: 0},
	z: new(Headword).Values(),
}

// String returns a string representation of this struct or record.
func (s Headword) String() string {
	res := make([]string, 3)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Headword: " + reform.Inspect(s.Headword, true)
	res[2] = "ArticleID: " + reform.Inspect(s.ArticleID, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Headword) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Headword,
		s.ArticleID,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Headword) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Headword,
		&s.ArticleID,
	}
}

// View returns View object for that struct.
func (s *Headword) View() reform.View {
	return HeadwordTable
}

// Table returns Table object for that record.
func (s *Headword) Table() reform.Table {
	return HeadwordTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Headword) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Headword) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Headword) HasPK() bool {
	return s.ID != HeadwordTable.z[HeadwordTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Headword) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int32(i64)
	} else {
		s.ID = pk.(int32)
	}
}

// check interfaces
var (
	_ reform.View   = HeadwordTable
	_ reform.Struct = (*Headword)(nil)
	_ reform.Table  = HeadwordTable
	_ reform.Record = (*Headword)(nil)
	_ fmt.Stringer  = (*Headword)(nil)
)

func init() {
	parse.AssertUpToDate(&HeadwordTable.s, new(Headword))
}
