#!/bin/bash

systemctl daemon-reload
systemctl enable verbum.service
systemctl restart verbum.service

if [ ! -f /usr/local/share/verbum/config.yaml ]; then
    touch /usr/local/share/verbum/config.yaml
fi
