#!/bin/bash

set -e

chown root:root /usr/local/bin/verbum
chmod +x /usr/local/bin/verbum
chown -R root:root /usr/local/share/verbum

if ! id verbum > /dev/null 2>&1; then
    useradd --system \
        --no-create-home \
        --home-dir /usr/local/share/verbum \
        --shell /usr/sbin/nologin \
        verbum
fi

if [ ! -f /usr/local/share/verbum/config.yaml ]; then
    touch /usr/local/share/verbum/config.yaml
fi

systemctl daemon-reload
systemctl enable verbum.service
systemctl restart verbum.service
