// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package dict

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type dictTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *dictTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("dicts").
func (v *dictTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *dictTableType) Columns() []string {
	return []string{"id", "title", "slug"}
}

// NewStruct makes a new struct for that view or table.
func (v *dictTableType) NewStruct() reform.Struct {
	return new(Dict)
}

// NewRecord makes a new record for that table.
func (v *dictTableType) NewRecord() reform.Record {
	return new(Dict)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *dictTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// DictTable represents dicts view or table in SQL database.
var DictTable = &dictTableType{
	s: parse.StructInfo{Type: "Dict", SQLSchema: "", SQLName: "dicts", Fields: []parse.FieldInfo{{Name: "ID", Type: "int32", Column: "id"}, {Name: "Title", Type: "string", Column: "title"}, {Name: "Slug", Type: "string", Column: "slug"}}, PKFieldIndex: 0},
	z: new(Dict).Values(),
}

// String returns a string representation of this struct or record.
func (s Dict) String() string {
	res := make([]string, 3)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Title: " + reform.Inspect(s.Title, true)
	res[2] = "Slug: " + reform.Inspect(s.Slug, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Dict) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Title,
		s.Slug,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Dict) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Title,
		&s.Slug,
	}
}

// View returns View object for that struct.
func (s *Dict) View() reform.View {
	return DictTable
}

// Table returns Table object for that record.
func (s *Dict) Table() reform.Table {
	return DictTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Dict) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Dict) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Dict) HasPK() bool {
	return s.ID != DictTable.z[DictTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Dict) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int32(i64)
	} else {
		s.ID = pk.(int32)
	}
}

// check interfaces
var (
	_ reform.View   = DictTable
	_ reform.Struct = (*Dict)(nil)
	_ reform.Table  = DictTable
	_ reform.Record = (*Dict)(nil)
	_ fmt.Stringer  = (*Dict)(nil)
)

func init() {
	parse.AssertUpToDate(&DictTable.s, new(Dict))
}
