// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package article

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type articleTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *articleTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("articles").
func (v *articleTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *articleTableType) Columns() []string {
	return []string{"id", "content"}
}

// NewStruct makes a new struct for that view or table.
func (v *articleTableType) NewStruct() reform.Struct {
	return new(Article)
}

// NewRecord makes a new record for that table.
func (v *articleTableType) NewRecord() reform.Record {
	return new(Article)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *articleTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// ArticleTable represents articles view or table in SQL database.
var ArticleTable = &articleTableType{
	s: parse.StructInfo{Type: "Article", SQLSchema: "", SQLName: "articles", Fields: []parse.FieldInfo{{Name: "ID", Type: "int32", Column: "id"}, {Name: "Content", Type: "string", Column: "content"}}, PKFieldIndex: 0},
	z: new(Article).Values(),
}

// String returns a string representation of this struct or record.
func (s Article) String() string {
	res := make([]string, 2)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Content: " + reform.Inspect(s.Content, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Article) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Content,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Article) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Content,
	}
}

// View returns View object for that struct.
func (s *Article) View() reform.View {
	return ArticleTable
}

// Table returns Table object for that record.
func (s *Article) Table() reform.Table {
	return ArticleTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Article) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Article) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Article) HasPK() bool {
	return s.ID != ArticleTable.z[ArticleTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Article) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int32(i64)
	} else {
		s.ID = pk.(int32)
	}
}

// check interfaces
var (
	_ reform.View   = ArticleTable
	_ reform.Struct = (*Article)(nil)
	_ reform.Table  = ArticleTable
	_ reform.Record = (*Article)(nil)
	_ fmt.Stringer  = (*Article)(nil)
)

func init() {
	parse.AssertUpToDate(&ArticleTable.s, new(Article))
}
