name: Verbum CI

on: [push, pull_request]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm ci
    - run: make fe-lint
    - run: make fe-build
    - uses: actions/upload-artifact@v4
      with:
        name: frontend-bundle
        path: frontend/dist/
        if-no-files-found: error

  build-backend:
    runs-on: ubuntu-latest
    needs:
    - build-frontend
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.22'
    - uses: actions/download-artifact@v4
      with:
        name: frontend-bundle
        path: frontend/dist/
    - run: go test -v ./...
    - run: make build-ci
    - uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          verbum
        if-no-files-found: error

  package:
    runs-on: ubuntu-latest
    needs:
    - build-backend
    - build-frontend
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v4
      with:
        name: binaries
    - uses: actions/download-artifact@v4
      with:
        name: frontend-bundle
        path: frontend/dist/
    - run: deploy/deb.bash
    - uses: actions/upload-artifact@v4
      with:
        name: verbum.deb
        path: deploy/verbum.deb
        if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs: package
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4
      with:
        name: verbum.deb
        path: deploy/
    - run: dpkg --info deploy/verbum.deb
    - run: deploy/deploy.bash
      env:
        ID_ED25519: ${{ secrets.ID_ED25519 }}
